It is polindrome
hihilisk/study pull request #3
Opened 2019-07-09 09:37 UTC by hihilisk

2019-07-09 12:52 UTC, hihilisk commented on palindrome/palindrome.rb
>    end
в ходе написания функции я записывал значения в переменную и возвращал ее через return (дабы убедиться что все работает штатно) , так и собрал ее, а потом до меня дошло что у меня в принципе нет необходимости хранить результаты преобразований

2019-07-09 13:19 UTC, hihilisk commented on palindrome/palindrome.js
>        return 'It`s not a palindrome';
const palindrome = string => (string === string.split("").reverse().join("")) ? 'It`s a palindrome' : (string.replace(/\s/g,'') === string.replace(/\s/g,'').split("").reverse().join("")) ? 'It`s a palindrome, no spaces' : 'It`s not a palindrome';

и оно работает))))

2019-07-09 13:40 UTC, hihilisk commented on palindrome/palindrome.js
>        return 'It`s not a palindrome';
в ходе написания функции я записывал значения в переменную и возвращал ее через return (дабы убедиться что все работает штатно) , так и собрал ее, а потом до меня дошло что у меня в принципе нет необходимости хранить результаты преобразований

2019-07-09 13:45 UTC, alexander-maxa requested changes

2019-07-09 13:45 UTC, UnlimNET commented on palindrome/palindrome.js
> +function palindrome (string) {
function palindrome(value) {

2019-07-09 13:45 UTC, UnlimNET commented on palindrome/palindrome.js
> +  if (string === string.split("").reverse().join("")) {
string === string.split('').reverse().join('')

2019-07-09 13:45 UTC, UnlimNET commented on palindrome/palindrome.js
> +  } else if (string.replace(/\s/g,'') === string.replace(/\s/g,'').split("").reverse().join("") ) {
string.replace(/\s/g,'' - вынеси в переменную

2019-07-09 13:45 UTC, UnlimNET commented on palindrome/palindrome.rb
> +  elsif string.gsub(' ', '') == string.reverse.gsub(' ', '')
Может быть сразу удалить пробелы, чтобы потом не делать это два раза?

2019-07-09 14:40 UTC, UnlimNET commented on palindrome/palindrome.js
> +  if (string===string.split('').reverse().join('')) {
пробелы?

2019-07-09 14:42 UTC, UnlimNET commented on palindrome/palindrome.js
> +  let stringReplaceSpace=string.replace(/\s/g,'');
строкаЗаменитьПробелы - это больше похоже на метод

Во-первых, не string, а value (string очень созвучно с типом) я об этом писал, во вторых старайся не использовать глаголы в именах переменных. Можно было бы назвать newValue or valueWithNoSpaces

2019-07-13 17:35 UTC, UnlimNET commented on palindrome/palindrome.js
> +  let valueWithNoSpaces = value.replace(/\s/g,'');
const

2019-07-13 17:36 UTC, UnlimNET commented on palindrome/palindrome.js
> +  let valueWithNoSpaces = value.replace(/\s/g,'');
value.replace(/\s/g, '');

2019-07-13 17:39 UTC, UnlimNET commented on palindrome/palindrome.rb
> +  elsif string_no_spaces == string_no_spaces.reverse
string_with_no_spaces

2019-07-23 11:18 UTC, merged